<?xml version="1.0" encoding="utf-8"?><Database Name="DotNetDB" Class="MyLocalDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ingefin.ensimag.fr;Initial Catalog=DotNetDB;Persist Security Info=True;User ID=etudiant" SettingsObjectName="ErrorHedging.Properties.Settings" SettingsPropertyName="DotNetDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HistoricalShareValues" Member="HistoricalShareValues">
    <Type Name="HistoricalShareValue">
      <Column Name="id" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="value" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>